### ISSUE TITLE
Need help please, I just can not get it to work.

### ISSUE THREAD

**Issue by Robiv8** [Ax-LED/MMM-Podcast2#2]
My Mirror is working and this:
omxplayer -ohdmi /opt/vc/src/hello_pi/hello_video/test.h264
is also working and the video is playing over the mirror.
Maybe I should mention that I have 5 buttons and all work. The pages change without hesitation.

But I don't now how to implement the code for podcast2 and how?
Can you help me.

An excerpt from the config file.
If you need other information, I like to put it in.
my config.js

```
modules: [
{
module: 'MMM-Page-Selector',
position: 'top_bar',
config: {
defaultPage: "haupt", ///"main",
displayTitle: true, //false,
selectPageNotif: ["SELECT_PAGE"],
incrementPageNotif: ["PAGE_UP"],
decrementPageNotif: ["PAGE_DOWN"]
}
},
{    module: 'MMM-Remote-Control'
    // uncomment the following line to show the URL of the remote control on the mirror
    // , position: 'bottom_left'
    // you can hide this module afterwards from the remote control itself
},
{
module: "alert",
name: "alert"
},
{
    module: "notification",
    name: "notification",
    position: "top_bar"
},
{
    module: 'MMM-Buttons',
    config: {
        maxShortPressTime: 500,
        minLongPressTime: 2000,
        buttons: [
....
{
                pin: 23, //The pin that connects your first button
                name: "Fuenfte Seite", //Or whatever you really want
                longPress: { //longPress or shortPress doesnt matter. Really it's just the stuff on the inside that matters.
                    notification: "BUTTON_PRESSED",
                    payload: "fuenfte" //Or whatever page you want
                },
                shortPress: {
                    notification: "PAGE_SELECT",
                    payload: "fuenfte" //Or whatever page you want
                }
            },
....
        ]
    }
},
....
{
    module: "MMM-Podcast2",
    name: "podcast2",
    config: {
    feedUrl: "https://www.tagesschau.de/export/video-podcast/webxl/tagesschau-in-100-sekunden_https/",
    omxargs: " --win 320,180,1600,900  -o both "
}
},
.....
],
pages: {
  fuenfte: {
    "newsfeed2": "top_center",
    "podcast2": "middle_center"
  },
  sechste: {
    "DigitalClock": "middle_center",
    "WetterStgt": "top_right"
  }
},
exclusions: [
  "MMM-page-indicator",
  "MMM-Cursor",
  "notification",
  "alert"
]
};
```
With a short press of the button 5 the page appears and shows only the newsfeed, then after a long press nothing happens. Here should then come the podcast.

Or should I put this into the MM forum? Maybe someone can give me a tip as well.

**Comment by Ax-LED** [comment]
@Robiv8 
English text see below
Da du MMM-Remote-Control installiert hast kannst du MMM-Podcast2 hiermit testen. (Voraussetzung: dein Spiegel ist per Browser im gleichen Netzwerk erreichbar). Öffne einen Broswer und gib folgendes ein: `http://yourmmip:8080/remote?action=NOTIFICATION&notification=BUTTON_PRESSED`
Danach sollte innerhalb von 3 Sekunden die Tagesschau auf deinem Spiegel starten.
Wenn das klappt, sehen wir weiter.

Gruß

As you have MMM-Remote-Control installed you can test MMM-Podcast2 with MMM-Remote-Control first, to make sure it works at all. (Requirement: Your mirror is reachable by browser in the same network). Open browser and enter `http://yourmmip:8080/remote?action=NOTIFICATION&notification=BUTTON_PRESSED`. So Tagesschau should start on the mirror within 3 seconds. If this work, we take the next step.

AxlED

**Comment by Robiv8** [comment]
English text see below

Vielen Dank dafür,
Ich habe mal zum Testen ein Frisches MM Aufgesetzt und nur Remote-Control und Podcast2 installiert.
Und! Es funzt :-)
Jetzt baue ich meine ursprüngliche nach und schaue woran es liegen könnte.
Bei fragen melde ich mich :-)

Thanks a lot for this,
I set up a fresh MM for testing and just installed remote control and podcast2.
And! It works :-)
Now I continue to build and see what it could be.
If you have questions I will contact you :-)

Robi
