### ISSUE TITLE
Upgrade to new notifications like "START_STREAM"/"STOP_STREAM"?

### ISSUE THREAD

**Issue by StefanMeGit** [Ax-LED/MMM-Podcast2#4]
Any chance to use different notifications with this module? I don't want to use the BUTTON_PRESSED to start and stop the stream. Specially because I want to stop the stream also on different "gestures" or other buttons.

**Comment by Ax-LED** [comment]
@StefanMeGit 
Your request is possible (in general), feel free to fork the module. Have a look at line 51 of MMM-Podcast2.js 
Here you can put in the modified code for your request.
AxLED

**Comment by StefanMeGit** [comment]
Thanks, i ll take a look on the weekend!
