### ISSUE TITLE
Bluetoothspeaker doesn't work

### ISSUE THREAD

**Issue by JosefJantzen** [Ax-LED/MMM-Podcast2#6]
Hi,
your module works fine with analog speaker but I would like to use my Alexa as bluetoothspeaker. The bluetoothspeaker doesn't work only with your module. Is the omxplayer the problem?

**Comment by Ax-LED** [comment]
@JoChef2 
Hi, if you search the web you will find some results, that omxplayer doesnt support audio via bluetooth.

AxLED
