### ISSUE TITLE
No video screen after updating raspberry

### ISSUE THREAD

**Issue by Kevinho195** [Ax-LED/MMM-Podcast2#7]
Hi,

I love this Podcast to watch in the morning before I go to work. But since last week I get no video on my screen. I did not change any modules or configs. I just updated my raspberry via sudo apt update. Has anyone else problems after updating his raspi?

My logs are showing that my notification was successfull. Is there some text missing in the end?

`0|mm  | Initializing new module helper ...
0|mm  | Module helper loaded: MMM-GooglePhotos
0|mm  | Initializing new module helper ...
0|mm  | Module helper loaded: MMM-quote-of-the-day
0|mm  | Initializing new module helper ...
0|mm  | Module helper loaded: MMM-MyScoreboard
0|mm  | No helper found for module: MMM-AirQuality.
0|mm  | No helper found for module: MMM-Advent.
0|mm  | Initializing new module helper ...
0|mm  | Module helper loaded: MMM-NowPlayingOnSpotify
0|mm  | No helper found for module: MMM-page-indicator.
0|mm  | All module helpers loaded.
0|mm  | Starting server on port 8080 ... 
0|mm  | Server started ...
0|mm  | Connecting socket for: updatenotification
0|mm  | Connecting socket for: calendar
0|mm  | Starting node helper for: calendar
0|mm  | Connecting socket for: MMM-Podcast2
0|mm  | Connecting socket for: MMM-MovieListings
0|mm  | MMM-MovieListing helper started...
0|mm  | Connecting socket for: newsfeed
0|mm  | Starting module: newsfeed
0|mm  | Connecting socket for: mvgmunich
0|mm  | Starting module helper: mvgmunich
0|mm  | Connecting socket for: MMM-AVStock
0|mm  | Connecting socket for: MMM-SoccerLiveScore
0|mm  | MMM-SoccerLiveScore helper started...
0|mm  | Connecting socket for: MMM-Events
0|mm  | Starting node_helper for: MMM-Events
0|mm  | Connecting socket for: MMM-Remote-Control
0|mm  | Starting node helper for: MMM-Remote-Control
0|mm  | Connecting socket for: MMM-Wunderlist-Enhanced
0|mm  | Connecting socket for: MMM-GooglePhotos
0|mm  | MMM-GooglePhotos started
0|mm  | Connecting socket for: MMM-quote-of-the-day
0|mm  | MMM-quote-of-the-day helper started
0|mm  | Connecting socket for: MMM-MyScoreboard
0|mm  | Starting node_helper for module [MMM-MyScoreboard]
0|mm  | Connecting socket for: MMM-NowPlayingOnSpotify
0|mm  | Sockets connected & modules started ...
0|mm  | Launching application.
0|mm  | Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/anniandkevini%40gmail.com/private-2d32da5d4a66c551ffaa23bfbe0f2365/basic.ics - Interval: 300000
0|mm  | Create new calendar fetcher for url: https://www.officeholidays.com/ics-local-name/germany/bavaria - Interval: 300000
0|mm  | Starting node helper for: MMM-Podcast2
0|mm  | Create new news fetcher for url: http://www.tagesschau.de/xml/rss2 - Interval: 300000
0|mm  | [AVSTOCK] Initialized.
0|mm  | MMM-GooglePhotos initialized after loading.
0|mm  | MMM-quote-of-the-day received a socket notification: INIT_HELPER - Payload: [object Object]
0|mm  | MMM-quote-of-the-day received a socket notification: GET_QUOTE - Payload: [object Object]
0|mm  | {
0|mm  |     "quoteText": "Failure will never overtake me if my determination to succeed is strong enough.  ",
0|mm  |     "quoteAuthor": "Og Mandino",
0|mm  |     "senderName": "",
0|mm  |     "senderLink": "",
0|mm  |     "quoteLink": "http://forismatic.com/en/70b5a19641/"
0|mm  | }
0|mm  | (node:5659) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
0|mm  | Refreshed access token because it has expired. Expired at: 22:04:13 now is: 22:04:14
0|mm  | Refreshed access token because it has expired. Expired at: 23:04:14 now is: 22:04:15
0|mm  | [GPHOTO] Scan finished : 206
0|mm  | Create new todo fetcher for list: Einkaufsliste - Interval: 60000
0|mm  | { Error
0|mm  |     at /home/pi/MagicMirror/modules/MMM-quote-of-the-day/node_modules/google-translate-api/index.js:105:17
0|mm  |     at process._tickCallback (internal/process/next_tick.js:68:7)
0|mm  |  code: 'BAD_REQUEST' }
0|mm  | MMM-Podcast2 PLAY:
`

Does anyone has an idea how to find out what may cause this problem?

My config:

{
			module: 'MMM-Podcast2',
			config: {
				feedUrl: 'https://www.tagesschau.de/export/video-podcast/webxl/tagesschau-in-100-sekunden_https/',
				refreshInterval: 1000 * 1800, //refreshs streaming link every 1800 seconds (30Min)
				omxargs: ' --win 10,200,1090,850  -o alsa:hw:1,0 '  //links,oben,rechts,unten
			}
		},

**Comment by Ax-LED** [comment]
@Kevinho195 
One of your modules is producing an error
rror 0|mm | at /home/pi/MagicMirror/modules/MMM-quote-of-the-day/node_modules/google-translate-api/index.js:105:17

So maybe this is the reason MMM-Podcast2 doesnt work anymore.
I didnt update my magicmirror and MMM-Podcast2 is still working.
I could also be, your omxplayer is not working anymore, are you able to test it with commandline?

AxLED

**Comment by Kevinho195** [comment]
@Ax-LED 
Thanks for your response! What would you recommend to test omxplayer? I am not sure how to test generel functionality

**Comment by Kevinho195** [comment]
@Ax-LED  
I did test my omxplayer via 

omxplayer --win 0,0,640,480 /opt/vc/src/hello_pi/hello_video/test.h264

and it did show the video on the screen during pm2 was running.

I disabled all my modules instead of Podcast2 but still no screen and no error log.

**Comment by manufunk** [comment]
I have the same issue. However I did not update anything. It suddenly just stopped working. I guess it is because of the "Tagesschau" link. Not sure if it was pointing to a video before. Now I just get some text as a result which omxplayer might not be able to handle. At least I see a generic error in the log file.

I also tried it with a local video and omxplayer works just fine. As it suddenly stopped I think the problem is due to a change of Tagesschau. Still looking for a solution but no luck so far. Any help appreciated.

**Comment by Ax-LED** [comment]
@Manu206 
I tried it with my MM today (untouched for a few month now, means i didnt update anything for a few month) an it worked. My module works as follows:
- it takes the url of the config an convert it to json
- after that it gets the value json.rss.channel.item.enclosure.url (which is the direct link to the mp4 file)
- the value of json.rss.channel.item.enclosure.url needs to be updated serveral times, as tagesschau changes the direct link of the mp4 several times a day.

Can you send me some details:
- error log
- your config of MMM-Podcast2
- which Raspberry are you using

AxLED

**Comment by thl81** [comment]
Hallo,
hatte das gleiche Problem. Ich konnte es beheben indem ich das "-o both" in der Config weggelassen habe... 
Vielleicht hilft das.
Gruß thl

**Comment by Ax-LED** [comment]
Hallo THL,
danke für deinen Tipp, vielleicht haben sich die Parameter des omxplayers geändert.

hi thl,
thanks for the hint, maybe the parameters of omxplayer have changed.

AxLED

**Comment by Kevinho195** [comment]
I solved the problem by reinstalling raspbian and MagicMirror. It took my almost a day but the module is running again!

How do you guys control the volume of the stream?
