### ISSUE TITLE
Module not running using MMM-Page-Selector

### ISSUE THREAD

**Issue by RolSch01** [Ax-LED/MMM-Podcast2#8]
Hi. 
I was running it in a single paged setup for some time and was very happy with it.
Now i switched to a multi page setup using MMM-Page-Selector and couldn't get your module running.
After some investigation it showed up, that the streamurl is blank when the playback is started. (which is not in standalone mode)
Reason is, that all modules are "deactivated" by MMM-Page-Selector shortly after startup and when not in use.
This leads to some initialization notifications not being processed. Furthermore the refresh mechanism does not work.
I did some simple changes and got it running. 
I defined 
var lastUpdate = 0;
var playbackPending = false;

On BUTTON_PRESSED check (Date.now() - lastUpdate) > interval? If yes, update first (set playbackPending = true, lastUpdate = Date.now() ) and start playback on DATA notification received (if playbackPending===true). Otherwise start playback directly.

Furthermore I added a PODCAST_STOPPED message on EXEC-command returned. Otherwise you need two notifications the next time you start playback since isPlaying is still true.

Hope you are still maintaining this module. If not may I use your code to fork a new one?

Best regards

**Comment by Ax-LED** [comment]
Hi RolSch01,
can you please tell me how you interact with MMM-Page-Selector (by Hyperlink, notification system or hardware on pi), as i tried to get MMM-Page-Selector up and failed. I made a config with only to pages and i am not able to switch between them.
So i can not reproduce your problem to fix it.
Regards 
AxLED

**Comment by Ax-LED** [comment]
Hi RolSch01,

maybe this is the solution for your problem.
https://github.com/Ax-LED/MMM-Podcast2/issues/3#issuecomment-455306957

Regards

AxLED

**Comment by Ax-LED** [comment]
Hi @RolSch01,
did you see my post with possible solutions?
Regards

AxLED

**Comment by RolSch01** [comment]
Hi @Ax-LED.
Sorry for the late response.
I was quite busy.

I checked the above solution and it seems to solve the problem.
Was not aware of the "exclusions" config of PageSelector.

Thank you.

Regards
RolSch01
